name: elcontrasteapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_html: ^3.0.0
  http: ^1.5.0
  just_audio: 0.9.36
  just_audio_background: 0.0.1-beta.11
  provider: ^6.1.5+1
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icon/
