// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmsYbedCQkAPIzo0Vrbvnfa1M9z86Qzg',
    appId: '1:146644960889:android:9e487ba1b2e39ca8ce76a8',
    messagingSenderId: '146644960889',
    projectId: 'elcontrastenoticias-f0ac1',
    storageBucket: 'elcontrastenoticias-f0ac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxhDJisSmM6Fson6peiOMdC8abOVzcsI',
    appId: '1:146644960889:ios:303509a17845a3aece76a8',
    messagingSenderId: '146644960889',
    projectId: 'elcontrastenoticias-f0ac1',
    storageBucket: 'elcontrastenoticias-f0ac1.firebasestorage.app',
    iosBundleId: 'com.davidsanchez.elcontrastenoticiasapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcIPniSp1zQfWcTWiE0e0NR_2bn2KutE',
    appId: '1:146644960889:web:80f0775213651fccce76a8',
    messagingSenderId: '146644960889',
    projectId: 'elcontrastenoticias-f0ac1',
    authDomain: 'elcontrastenoticias-f0ac1.firebaseapp.com',
    storageBucket: 'elcontrastenoticias-f0ac1.firebasestorage.app',
    measurementId: 'G-32625W8CYY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxhDJisSmM6Fson6peiOMdC8abOVzcsI',
    appId: '1:146644960889:ios:4b0e71cf6593fe28ce76a8',
    messagingSenderId: '146644960889',
    projectId: 'elcontrastenoticias-f0ac1',
    storageBucket: 'elcontrastenoticias-f0ac1.firebasestorage.app',
    iosBundleId: 'com.example.elcontrasteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbcIPniSp1zQfWcTWiE0e0NR_2bn2KutE',
    appId: '1:146644960889:web:fb08f504ecbc9689ce76a8',
    messagingSenderId: '146644960889',
    projectId: 'elcontrastenoticias-f0ac1',
    authDomain: 'elcontrastenoticias-f0ac1.firebaseapp.com',
    storageBucket: 'elcontrastenoticias-f0ac1.firebasestorage.app',
    measurementId: 'G-QMEMH3PFWW',
  );
}
